# Generated by Django 6.0.3 on 2026-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesatransaction',
            old_name='amount',
            new_name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='savings_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
