"""
Django settings for AirSave Fintech project.
Generated by 'django-admin startproject' for 3rd Year CS Project.
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from decouple import config
import dj_database_url
from dj_database_url import parse as db_url
load_dotenv()

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings
SECRET_KEY = config('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1', 
    'glamour-askew-footwork.ngrok-free.dev',
    '.onrender.com',
    'airsave.vercel.app', 
]

# Application definition
INSTALLED_APPS = [
    'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'whitenoise.runserver_nostatic',
    
    # AirSave Custom Modules
    'core',      # Identity & User Management
    'wallet',    # Ledger & Rounding Engine
    'payments',  # M-Pesa Daraja API Integration
    'analytics', # Financial Insights
]

# THE CORE SECURITY RULE: Use the Phone-based User Model
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'airsave_backend.urls'

# CORS SETTINGS (Critical for React communication)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    #"https://airsave.vercel.app",
]

# Allow Vercel preview branches
#CORS_ALLOWED_ORIGIN_REGEXES = [
   # r"^https://.*\.vercel\.app$",
#]

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com', 
    'https://airsave.vercel.app', 
    'https://glamour-askew-footwork.ngrok-free.dev',
    'http://localhost:5173', 
]

# JWT Settings for Secure Session Management
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Production Security Handled by Trevor & Saners
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'airsave_backend.wsgi.application'

BASE_DIR = Path(__file__).resolve().parent.parent

# Check if we are running on Render (Render sets the DATABASE_URL env var)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Use Postgres on Render
    DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
    )
}
else:
    # Keep SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi' 
USE_I18N = True
USE_TZ = True

# Static files
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Admin Branding (AirSave Edition)
ADMIN_SITE_HEADER = 'AIRSAVE FINTECH ADMINISTRATION'
ADMIN_SITE_TITLE = 'AirSave Portal'
ADMIN_INDEX_TITLE = 'Financial Systems Control'

# JAZZMIN Config
JAZZMIN_SETTINGS = {
    "site_title": "AirSave",
    "site_header": "AIRSAVE",
    "site_brand": "AirSave Fintech",
    "welcome_sign": "Authorized Access Only",
    "copyright": "AirSave Team",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "core.User": "fas fa-user-shield",
        "wallet.Wallet": "fas fa-wallet",
        "wallet.Transaction": "fas fa-exchange-alt",
        "core.AuditLog": "fas fa-clipboard-list",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "theme": "flatly", # Professional fintech blue/white theme
}