# Generated by Django 6.0.3 on 2026-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usersavingsanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savinggoal',
            name='roundup_base',
            field=models.IntegerField(default=10),
        ),
    ]
